- quickstart/llmd-infra-installer.sh
- Remnant from the pvc only days
- Remove CRB cleanup since not installed in infra
> Remove minikube pv cleanup

- quickstart/examples/pd-disaggregation/gaie-pd/values.yaml
- quickstart/examples/pd-disaggregation/helmfile.yaml
- quickstart/examples/simple/gaie-simple/values.yaml
- quickstart/examples/simple/helmfile.yaml
- quickstart/examples/simple/ms-simple/values.yaml
cc @nerdalert and @robertgshaw2-redhat - we got the new upstream EPP image and are waiting on the new `inference-scheduler` one. This setup worked for me
> Update for gaie 0.5.0 rc2

- charts/llm-d-infra/values.yaml
- quickstart/examples/simple/README.md
Tracking in #27 for reversion back to Istio once resolved.
> Temporarily swap to kgateway as the default provider

- quickstart/examples/sim/ms-sim/values.yaml
> bumping inference simulator image

- .github/scripts/e2e/e2e-validate.sh
- .github/workflows/e2e-aws.yaml
> Add ec2 e2e for the simple-infra deployment

- quickstart/examples/pd-disaggregation/gaie-pd/values.yaml
- quickstart/examples/pd-disaggregation/helmfile.yaml
- quickstart/examples/prefix-cache-aware/helmfile.yaml
- quickstart/examples/sim/gaie-sim/values.yaml
- quickstart/examples/sim/helmfile.yaml
- quickstart/examples/simple/gaie-simple/values.yaml
- quickstart/examples/simple/helmfile.yaml
> Update epp release candidate image

- .github/workflows/e2e-aws.yaml
> Update deployment name in accelerated e2e

- charts/llm-d-infra/README.md
- charts/llm-d-infra/templates/gateway-infrastructure/configmap.yaml
- charts/llm-d-infra/templates/gateway-infrastructure/gatewayparameters.yaml
- charts/llm-d-infra/values.schema.json
- charts/llm-d-infra/values.schema.tmpl.json
- charts/llm-d-infra/values.yaml
cc @tlrmchlsmth this should solve your issue
> enable specifying envoy resources

- helpers/kind-testing/kind-config.yaml
@Gregory-Pereira bringing this over as I noticed this job complaining https://github.com/llm-d-incubation/llm-d-infra/actions/runs/16476768187/job/46580405113
> Add missing config for the chart test job

- quickstart/examples/pd-disaggregation/README.md
- quickstart/examples/pd-disaggregation/destinationRule.yaml
- quickstart/examples/pd-disaggregation/gaie-pd/values.yaml
- quickstart/examples/pd-disaggregation/helmfile.yaml
SUMMARY:
- use latest images 
- switch to use a different namespace
> [PD Scoring] Update P/D Scoring To Use Load-Aware Balancing

- quickstart/examples/inference-scheduling/gaie-inference-scheduling/values.yaml
- quickstart/examples/inference-scheduling/helmfile.yaml
- quickstart/examples/pd-disaggregation/gaie-pd/values.yaml
- quickstart/examples/pd-disaggregation/helmfile.yaml
- quickstart/examples/precise-prefix-cache-aware/gaie-kv-events/values.yaml
- quickstart/examples/precise-prefix-cache-aware/helmfile.yaml
- quickstart/examples/sim/gaie-sim/values.yaml
- quickstart/examples/sim/helmfile.yaml
- update examples to latest versions
- NOTE: still need to bump wide-ep examples separately
> [Release] Bump Versions

- helpers/scripts/test-requests.sh
- Common script for user to do a quick smoke test for debugging deployments.
Sample output with verbose where a user can see the kubectl run invocation to assist with debugging:
```
$ ./test-request.sh --verbose
Namespace: llm-d
Model ID:  none; will be discovered from first entry in /v1/models
-> Discovering decode pod…
✅ Success: Found decode pod at 10.244.0.17
1 -> GET /v1/models from decode pod…
- Running command:
kubectl run --rm -i curl-2257 \
--namespace "llm-d" \
--image=curlimages/curl --restart=Never -- \
curl -sS --fail http://10.244.0.17:8000/v1/models \
-H 'accept: application/json' \
-H 'Content-Type: application/json'
✅ Success
{"object":"list","data":[{"id":"random","object":"model","created":1753320844,"owned_by":"vllm","root":"random","parent":null}]}pod "curl-2257" …
```
> Add a validation script

- quickstart/examples/inference-scheduling/gaie-inference-scheduling/values.yaml
- quickstart/examples/pd-disaggregation/gaie-pd/values.yaml
cc @robertgshaw2-redhat @ahg-g 
Relates to: https://llm-d.slack.com/archives/C08SBNRRSBD/p1753332557675179?thread_ts=1753329718.098549&cid=C08SBNRRSBD
> Cleanup inference scheduling example

- quickstart/examples/inference-scheduling/ms-inference-scheduling/values.yaml
- quickstart/examples/pd-disaggregation/ms-pd/values.yaml
- quickstart/examples/precise-prefix-cache-aware/ms-kv-events/values.yaml
- quickstart/examples/wide-ep-lws/ms-wide-ep/values.yaml
> bumping to vllm rc image

- quickstart/examples/README.md
Use the content that will go on the readme.
> Provide a landing page for quickstart/examples on well-lit paths

- quickstart/examples/precise-prefix-cache-aware/gaie-kv-events/values.yaml
> removing decode filters on precise example

- CODEOWNERS
cc @nerdalert @robertgshaw2-redhat PTAL
> implementing codeowners

- quickstart/examples/inference-scheduling/README.md
- quickstart/examples/inference-scheduling/ms-inference-scheduling/values.yaml
- quickstart/examples/pd-disaggregation/README.md
- quickstart/examples/pd-disaggregation/gke.md
- quickstart/examples/pd-disaggregation/ms-pd/values.yaml
- quickstart/examples/precise-prefix-cache-aware/README.md
- quickstart/examples/precise-prefix-cache-aware/ms-kv-events/values.yaml
- quickstart/examples/sim/README.md
- quickstart/examples/wide-ep-lws/README.md
- quickstart/examples/wide-ep-lws/ms-wide-ep/values.yaml
cc @nerdalert one last round of tests
> updating examples with production image

- quickstart/README.md
- quickstart/docs/infra-providers/openshift/README-openshift.md
- quickstart/examples/README.md
- quickstart/examples/precise-prefix-cache-aware/README.md
Some more broken links found from our documentation work.
> Fix broken links

- quickstart/examples/pd-disaggregation/gke.md
- quickstart/examples/precise-prefix-cache-aware/README.md
@nerdalert @Gregory-Pereira 
TIL that all items in numbered lists need the prefix 1. according to the markdown linter rules in place 🤷
> more pre-commit fixes

- .github/workflows/e2e-accelerator-test.yaml
- `/run-e2e` - kgateway with precise and scheduler
- `/run-e2e-istio` - istio with precise and scheduler
- Jobs require write roles to trigger
> Add PR comment triggers for accelerated e2e

- quickstart/examples/inference-scheduling/README.md
- quickstart/examples/inference-scheduling/ms-inference-scheduling/values.yaml
- quickstart/examples/pd-disaggregation/ms-pd/values.yaml
- quickstart/examples/precise-prefix-cache-aware/ms-kv-events/values.yaml
- quickstart/examples/sim/README.md
- quickstart/examples/sim/ms-sim/values.yaml
- quickstart/examples/wide-ep-lws/ms-wide-ep/values.yaml
- quickstart/istio-workaround.md
- quickstart/llmd-infra-installer.sh
This should go in after https://github.com/llm-d-incubation/llm-d-modelservice/pull/70. 
Will also add documentation for enabling podmonitor creation if the podmonitor CRD exists (if Prometheus operator exists)
> add podmonitors for prefill,decode examples

- .github/workflows/e2e-pd-disaggregation-accelerator-test.yaml
> Add accelerated e2e coverage for pd-disaggregation

- .github/workflows/e2e-wide-ep-accelerator-test.yaml
Consistent formatting on the llm-d installer and wrapping LWS installs in ssh
> wrapping the lws install command in ssh to run remotely
